format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[nodejs]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
min_time = 60_0000

[memory_usage]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
trim_at = ".fritz.box"
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
#[character]     # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green) "
#error_symbol = "[✗](bold red) "

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false

[gcloud]
disabled = true